### PR TITLE
feat: Added a new rehype plugin to plugins.md

### PR DESCRIPTION
**Pull request by ITZSHOAIB**
### Initial checklist

* [x] I read the support docs 
* [x] I read the contributing guide 
* [x] I agree to follow the code of conduct 
* [x] I searched issues and couldn’t find anything (or linked relevant results below) 
* [x] If applicable, I’ve added docs and tests

### Description of changes

Added a rehype plugin into the plugins.md file.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Thanks for sharing @ITZSHOAIB ! 🙇 
Please see the check list above and check it off before the one below.

General feedback on what gets included in the plugins list:

> Some criteria to include packages in this list.
>
> - Some documentation with at least some instructions on how to use the package.
> - A CI job to run tests. (The tests are already there.)
> - A `prepack` script and CI job to build the types. (The JSDoc types are already there.)
> - The package should be published to npm.

source: https://github.com/syntax-tree/hast/pull/24#issuecomment-2015384111

For your plugin I'm seeing:
- [x] Documentation
- [ ] CI to run lint and tests
- [x] Job to generate types
- [x] Published to NPM

---

Some additional pointers.

1. Delivery readable JavaScript, not minified code to the registry https://github.com/ITZSHOAIB/rehype-code-group/blob/b2555a0abfd414c554f44a0111d9f913952fd0ae/package.json#L19
2. Use wider version ranges where possible, to allow package managers to deduplicate (E.G. `"rehype": "^13.0.0",`) https://github.com/ITZSHOAIB/rehype-code-group/blob/b2555a0abfd414c554f44a0111d9f913952fd0ae/package.json#L31-L34
3. Use Node16 resolution https://github.com/ITZSHOAIB/rehype-code-group/blob/b2555a0abfd414c554f44a0111d9f913952fd0ae/tsconfig.json#L5-L10
   > Because node16 and nodenext are the only module options that reflect the complexities of Node.js’s dual module system, they are the only correct module options for all apps and libraries that are intended to run in Node.js v12 or later, whether they use ES modules or not.

   https://www.typescriptlang.org/docs/handbook/modules/reference.html#node16-nodenext
- When you add tests, consider `node:test` or `vitest`, `jest` is known to break with ESM https://github.com/ITZSHOAIB/rehype-code-group/blob/b2555a0abfd414c554f44a0111d9f913952fd0ae/package.json#L47
- Your module appears to be side effect free, consider making it easier for build tools to figure that out https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by ITZSHOAIB** [comment]
> Thanks for sharing @ITZSHOAIB ! 🙇 Please see the check list above and check it off before the one below.
> 
> General feedback on what gets included in the plugins list:
> 
> > Some criteria to include packages in this list.
> > 
> > * Some documentation with at least some instructions on how to use the package.
> > * A CI job to run tests.
> > * A `prepack` script and CI job to build the types.
> > * The package should be published to npm.
> 
> source: [syntax-tree/hast#24 (comment)](https://github.com/syntax-tree/hast/pull/24#issuecomment-2015384111)
> 
> For your plugin I'm seeing:
> 
> * [x]  Documentation
> * [ ]  CI to run lint and tests
> * [x]  Job to generate types
> * [x]  Published to NPM
> 
> Some additional pointers.
> 
> 1. Delivery readable JavaScript, not minified code to the registry https://github.com/ITZSHOAIB/rehype-code-group/blob/b2555a0abfd414c554f44a0111d9f913952fd0ae/package.json#L19
> 2. Use wider version ranges where possible, to allow package managers to deduplicate (E.G. `"rehype": "^13.0.0",`) https://github.com/ITZSHOAIB/rehype-code-group/blob/b2555a0abfd414c554f44a0111d9f913952fd0ae/package.json#L31-L34
> 3. Use Node16 resolution https://github.com/ITZSHOAIB/rehype-code-group/blob/b2555a0abfd414c554f44a0111d9f913952fd0ae/tsconfig.json#L5-L10
>    > Because node16 and nodenext are the only module options that reflect the complexities of Node.js’s dual module system, they are the only correct module options for all apps and libraries that are intended to run in Node.js v12 or later, whether they use ES modules or not.
>    
>    
>    https://www.typescriptlang.org/docs/handbook/modules/reference.html#node16-nodenext
> 
> * When you add tests, consider `node:test` or `vitest`, `jest` is known to break with ESM https://github.com/ITZSHOAIB/rehype-code-group/blob/b2555a0abfd414c554f44a0111d9f913952fd0ae/package.json#L47
> * Your module appears to be side effect free, consider making it easier for build tools to figure that out https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

Thanks, @ChristianMurphy for a detailed reply.

1. Is there any issue if I minify the package? I have also included the actual source code in the NPM package with dtsMaps. So using IDE, if users navigate they will land on the source code. Could you please help me understand what the issue can be with minified javascript?
2. Wider range means? Lower versions?
3. I will look into this.

And regarding test, I will add tests using suggested libraries. Thanks!

**Comment by ChristianMurphy** [comment]
> Is there any issue if I minify the package? I have also included the actual source code in the NPM package with dtsMaps. So using IDE, if users navigate they will land on the source code. Could you please help me understand what the issue can be with minified javascript?

A lot, and the same goes for including polyfills and down leveling to earlier versions of the JavaScript standard.
Some highlights:
* It's a security risk as it makes it difficult to audit/review the actual running code (https://gist.github.com/joepie91/04cc8329df231ea3e262dffe3d41f848)
* Source maps don't replace readable code, are non-standard (currently), and don't work with every tool (https://www.briefs.fm/3-minutes-with-kent/221, https://github.com/tc39/source-map)
* It makes minification of usage of the library in apps worse https://stackoverflow.com/questions/48673408/should-javascript-npm-packages-be-minified
* bundle/build tools tend to add some wrapper bloat (https://e18e.dev/)

> Wider range means? Lower versions?

Version ranges are `~`, `^`, or `*` https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept

This does not mean lower default version, the package manager will still default to latest in the range.
It means a lower _minimum_ required version, this gives the package manager more opportunities to de-duplicate if it finds an older version already included in a lockfile or as a dependency of another library

**Comment by ITZSHOAIB** [comment]
@ChristianMurphy Thanks for the time and effort. So, what would you suggest?

1. Disable minification and serve only bundled js.
2. Remove sourcemaps, only js and dts would be sufficient.
3. Avoid bundlers at all and use TSC instead.
4. Should I make the package available only for esm? Or esm and cjs both? In the case of both esm and cjs, could you please help me with proper configuration examples for tsconfig and how to properly make cjs and esm available.

**Comment by ITZSHOAIB** [comment]
Any update????

**Review by ChristianMurphy — CHANGES_REQUESTED** [review]
Hey @ITZSHOAIB! 👋 
Nice to see the tests in place and the build output being more consumable.
Could you fill out the PR template here above, you don't seem to have completed it. That's the last remaining blocker

Not blocker, but would be nice to have.
* Use Node16 resolution https://github.com/ITZSHOAIB/rehype-code-group/blob/e1aea7bbbc0e80f9170fbeaccfeaa9986e3c8e26/tsconfig.json#L6-L7
* Consider widening your version ranges https://github.com/ITZSHOAIB/rehype-code-group/blob/e1aea7bbbc0e80f9170fbeaccfeaa9986e3c8e26/package.json#L34-L37, package managers will choose the latest in range, but allowing lower (down to 0.0 of a release) allows them to deduplicate more if there is a conflict)

**Comment by wooorm** [comment]
Please follow the PR template: write a description / check the checkboxes

**Review by ChristianMurphy — APPROVED** [review]

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Thanks!

**Pull request merged**
