### PR TITLE
Add rehype-color-chips to the list of plugins

### PR DESCRIPTION
**Pull request by shreshthmohan**
### Initial checklist

* [x] I read the support docs 
* [x] I read the contributing guide 
* [x] I agree to follow the code of conduct 
* [x] I searched issues and couldn’t find anything (or linked relevant results below) 
* [x] If applicable, I’ve added docs and tests

### Description of changes

Added a new rehype plugin to the list at `doc/plugins.md`

### CODE REVIEW

**Comment by wooorm** [comment]
Cool. If you’re interested, here’s how this works on GH. It’s limited, and GH-specific, but it adds a little blob:

```js
visit(tree, "element", function (node) {
  if (node.tagName === "code") {
    const value = toString(node);
    if (/^#[\da-f]{6}$/i.test(value)) {
      node.children.push({
        type: "element",
        tagName: "span",
        properties: {
          className: [
            "ml-1",
            "d-inline-block",
            "border",
            "circle",
            "color-border-subtle",
          ],
          style: "background-color: " + value + "; height: 8px; width: 8px;",
        },
        children: [],
      });
    }
  }
});
```

**Review by wooorm — APPROVED** [review]

**Comment by shreshthmohan** [comment]
Thank you! 

Changed to call color(value) only once. 

https://github.com/shreshthmohan/rehype-color-chips/commit/1d54a1f89e0839663e058a340bd2f2de2c2df4b1#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80

**Comment by remcohaszing** [comment]
Just a tip: `rehype-color-chips` is built as both ESM and CJS. However, the CJS build doesn’t work, because it has ESM-only dependencies. I recommend to remove it and publish as ESM only.

**Comment by shreshthmohan** [comment]
@remcohaszing will do. Thanks!

**Pull request merged**
