### PR TITLE
Add `rehype-mathml` to list of plugins

### PR DESCRIPTION
**Pull request by Daiji256**
### Initial checklist

* [x] I read the support docs 
* [x] I read the contributing guide 
* [x] I agree to follow the code of conduct 
* [x] I searched issues and couldn’t find anything (or linked relevant results below) 
* [x] If applicable, I’ve added docs and tests

### Description of changes

Add [`rehype-mathml`](https://github.com/Daiji256/rehype-mathml) to list of plugins

Rendering math with MathML is lightweight and supported by many browsers.
I wanted a plugin for rendering math with MathML, similar to `rehype-mathjax` and `rehype-katex`, so I have created `rehype-mathml`.

npm: [`@daiji256/rehype-mathml`](https://www.npmjs.com/package/@daiji256/rehype-mathml)

### CODE REVIEW

**Comment by wooorm** [comment]
Nice!

* a stable 1.0.0 release might be nice before adding it to this list
* readme could use more mentions/links of `temml`, the core library that does the work, whose options are supported — as a user looking through different math packages, I’d be interested in that!
* instead of the `result = unified()….parse(mathml).children` code, I strongly recommend https://github.com/syntax-tree/hast-util-from-html-isomorphic! It’s lighter especially in browsers, it’s a simpler API call, and it drops positional info (which are now incorrect)

**Comment by Daiji256** [comment]
Thank you for your comments.

>a stable 1.0.0 release might be nice before adding it to this list

Based on the advice given in this pull request, I was planning to make some adjustments and then release stable 1.0.0. Is it necessary to release stable 1.0.0 immediately?

>readme could use more mentions/links of temml, the core library that does the work, whose options are supported — as a user looking through different math packages, I’d be interested in that!

Do I need to describe the reasons for using temml? Or do I need to add the main options of temml to the README? Links to temml's options have already been included.

>instead of the result = unified()….parse(mathml).children code, I strongly recommend https://github.com/syntax-tree/hast-util-from-html-isomorphic! It’s lighter especially in browsers, it’s a simpler API call, and it drops positional info (which are now incorrect)

I wasn't aware of hast-util-from-html-isomorphic. I will make the necessary corrections.

**Comment by wooorm** [comment]
> Is it necessary to release stable 1.0.0 immediately?

No — but: this list is for recommended things; that conflicts with software in beta

> Do I need to describe the reasons for using temml? Or do I need to add the main options of temml to the README?

I was missing the first, yes, reasons to use this package over `rehype-mathjax` or `rehype-katex`. And that mostly has to do with `temml`!

**Comment by Daiji256** [comment]
I have also completed the fix for hast-util-from-html-isomorphic, and after determining that the main code is sufficient, I have released stable 1.0.0.

As you pointed out, the README lacked descriptions of the strengths of this plugin, which uses MathML, and the reasons for using `temml`, making it unclear. I have added those details.

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Thanks!

**Comment by ChristianMurphy** [comment]
Thanks @Daiji256! 👋 
Some other suggestions:
1. it doesn't look like the typescript types are published as part of 1.0.0, you may want to include those on npm https://www.npmjs.com/package/@daiji256/rehype-mathml
2. where possible use a wider minimum version in version ranges, to allow package managers to deduplicate if they already require a lower version (e.g. `"unified": "^11.0.5",`) https://github.com/Daiji256/rehype-mathml/blob/9cd35ed4ea3e8f734a22f068fc003553d3cdd93d/package.json#L37-L41
3. ESInterop  is not required and should be avoided in `node16` module mode https://github.com/Daiji256/rehype-mathml/blob/9cd35ed4ea3e8f734a22f068fc003553d3cdd93d/tsconfig.json#L7
4. The dependencies for this module should in theory also have valid types, and don't need to be skipped https://github.com/Daiji256/rehype-mathml/blob/9cd35ed4ea3e8f734a22f068fc003553d3cdd93d/tsconfig.json#L9
5. The types hast dependency appears in the code but not in the dependencies, you may want to declare it a dependency so yarn and pnpm work https://github.com/Daiji256/rehype-mathml/blob/9cd35ed4ea3e8f734a22f068fc003553d3cdd93d/lib/index.ts#L1

**Comment by Daiji256** [comment]
@ChristianMurphy 
Thank you for the suggestions! I’ll review them and make the necessary updates.

**Pull request merged**
