### PR TITLE
Update Actions

### PR DESCRIPTION
**Pull request by ChristianMurphy**
### Initial checklist

* [x] I read the support docs 
* [x] I read the contributing guide 
* [x] I agree to follow the code of conduct 
* [x] I searched issues and couldn’t find anything (or linked relevant results below) 
* [x] If applicable, I’ve added docs and tests

### Description of changes

setup-node now supports named versions.
codecov-action version 1 has been sunset and no longer functions

### CODE REVIEW

**Review by remcohaszing — APPROVED** [review]

**Comment by remcohaszing** [comment]
The tests are failing, because this package supports and is tested against Node.js 12, but CI installs the latest version of npm (9), which only supports Node.js 14 and upwards.

I see two solutions:

- Explicitly install npm 8 instead of the latest
- Drop support for Node.js 12

I suggest to use npm 8, as dropping Node.js 12 would be semver major, which seems a bit much if it’s just to fix CI. Even if Node.js 12 is dropped, I still suggest using a pinned npm version.

**Comment by wooorm** [comment]
I’m fine with upgrading Node in Actions. It does not have to equal dropping support for Node 12 in the shipped code.

Especially for the Node test runner I even have to even use Node 18: https://github.com/wooorm/longest-streak/blob/main/.github/workflows/main.yml.

**Comment by remcohaszing** [comment]
I do think we should test against all supported Node.js versions. CI has helped me catch errors due to the use of features unavailable in Node.js 12 before.

I am really looking forward to deprecation of Node.js 16, so I can start using the builtin test runner too :smile:

**Comment by wooorm** [comment]
I think it’s quite nice to have the lowest supported version of Node in there, but more important to not cut a major when it’s only to use some newer linters or testing tools.

> CI has helped me catch errors due to the use of features unavailable in Node.js 12 before.

It has helped me only a bit. I’ve more often seen bugs slip in anyway. Or it indeed failing on some linting/testing tool.
I’d say it’s particularly important to test on the oldest supported version if a) you’re writing something new (most of our stuff barely changes), b) you’re writing in a compile-to-JavaScript language where you’re using the latest TC39 proposals that are supposed to compile down to some older flavor of JavaScript (most of our code, other than ESM, uses features that have been around in JavaScript since ±ES6?)

**Comment by ChristianMurphy** [comment]
Rebased off latest, looks like CI is happy again

**Review by wooorm — APPROVED** [review]

**Pull request merged**
