### PR TITLE
Add `rehype-attr` to list of plugins

### PR DESCRIPTION
**Pull request by jaywcjlove**

### CODE REVIEW

**Comment by wooorm** [comment]
thanks @jaywcjlove!

**Comment by wooorm** [comment]
It’s probably a good idea to add an example with just rehype, even though it‘s mostly useful with coming from remark.

And you might want to remove the “used” comments afterwards?

**Comment by jaywcjlove** [comment]
> And you might want to remove the “used” comments afterwards?


I did not understand the meaning of `And you might want to remove the “used” comments afterwards?`


@wooorm

**Comment by wooorm** [comment]
I mean, given this input:

```html
<p>text</p><!--rehype:id=text-->
```

Now the output is (I believe):

```html
<p id="text">text</p><!--rehype:id=text-->
```

I propose something like this (optionally?)

```html
<p id="text">text</p>
```

**Comment by jaywcjlove** [comment]
@wooorm thx! I have added related documents.

**Comment by wooorm** [comment]
Cool!

I think it’s a pretty smart way of adding arbitrary attributes btw, nice find!

**Pull request merged**
