### PR TITLE
Add rehype-rewrite

### PR DESCRIPTION
**Pull request by jaywcjlove**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

Upgrade plugins list.

### CODE REVIEW

**Comment by wooorm** [comment]
- the function internally is called `remarkRewrite`, should that be `rehypeRewrite`?
- if you’re working with hast, you can use those types, instead of using `unist.Node` and casting things to `any`s and such. `unist-util-visit` has pretty awesome and cool types, that you can also use.
  - ```ts
    Plugin<[Options?] | [], HastRoot>
    ```
  - You could perhaps type the handler as [`BuildVisitor<HastRoot>`](https://github.com/syntax-tree/unist-util-visit/blob/5abd634adc89a235294711776c1cc32a3555bb49/complex-types.d.ts#L51)
- It might be better to only `visit` if there is a handle, rather than always visiting and then checking if `handle` is a function?

**Comment by jaywcjlove** [comment]
image

@wooorm Property 'value' does not exist on type `'Node<Data>'`.

**Comment by ChristianMurphy** [comment]
That is coming from using a generic `Node` type at https://github.com/jaywcjlove/rehype-rewrite/blob/fc291b9f5d08d2537c03d3eaaf336b4f97386c70/src/index.ts#L7

Where you probably want to use a hast root, like https://github.com/rehypejs/rehype/blob/ef34db54e9acbc10d1a70cc67e9daf1bc08eec6a/packages/rehype-parse/index.d.ts#L3

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/rehype-rewrite/commit/88bee159f60078b4ed6783a825e2867bcc0681f4

This is how I solved the type error. It doesn't seem to be perfect.
@ChristianMurphy @wooorm

**Pull request merged**
